apiVersion: v1
kind: Secret
metadata:
  name: sec-{{ .Values.application }}-{{ .Values.environment }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGOCONNECTION: "{{ .Values.mongodb_uri }}"

#data:
#  key1: value1 #base64encoded
#  key2: value2 #base64encoded