# Default values for ratings-api PROD.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: prod

image:
  repository: quay.io/swoturkey/ratings-api
  tag: master

###### SECRETS ######
mongodb_uri: "mongodb://sa:sa123@mongodb.ratingsapp:27017/ratingsdb"
